# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
development:
  adapter: mysql2
  encoding: utf8
  database: todo_base
  username: root
  password: root
  host: 0.0.0.0
  port: 3306
